version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - "3307:3306"
    networks:
      - my-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: flask-ng:latest
    container_name: flask-app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}

    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  my-network:
